### PR TITLE
Various 0.5.0 fixes

### PR DESCRIPTION
**Pull request by simonv3**

### CODE REVIEW

**Comment by whatSocks** [comment]
checking ...

**Comment by whatSocks** [comment]
**collapse logo to just be resonate on smaller screens**

Maybe it's good enough for now, on phone-size screens the UI like:

Screen Shot 2022-05-08 at 10 26 01 AM

v0.4.0 History Loads 2x #121 
paylist editing / viewing 

I can't log out - forever spinner on my user button -- so I can't log back in to test this

**Comment by simonv3** [comment]
> Maybe it's good enough for now, on phone-size screens the UI like:

Yeah I was focusing on the "desktop" sizes, but I can put a bit more effort into smaller screens to.

**Comment by simonv3** [comment]
Just added a PR that ads this: 

image

**Pull request merged**
